import tkinter as tk
from tkinter import ttk

def mostrar_datos(entry_nombre, entry_edad, entry_comuna, ventana, texto_box, combobox):
    nombre = entry_nombre.get()
    edad = entry_edad.get()
    comuna = entry_comuna.get()
    print(f"Nombre: {nombre}")
    print(f"Edad: {edad}")
    print(f"Comuna: {comuna}")
    texto = texto_box.get("1.0", tk.END)
    opcion = combobox.get()
    print(f"Texto: {texto}")
    print(f"Opción: {opcion}")
    ventana.destroy()
    ventana_gracias = tk.Tk()
    ventana_gracias.title("Gracias")
    ventana_gracias.geometry("300x200")
    label_gracias = tk.Label(ventana_gracias, text="Gracias por llenar el formulario")
    label_gracias.place(x=10, y=10)
    def finalizar():
        ventana_gracias.destroy()
    def ingresar_nuevamente():
        ventana_gracias.destroy()
        ventana_principal()
    boton_finalizar = tk.Button(ventana_gracias, text="Finalizar", command=finalizar)
    boton_finalizar.place(x=10, y=50)
    boton_ingresar_nuevamente = tk.Button(ventana_gracias, text="Ingresar nuevamente", command=ingresar_nuevamente)
    boton_ingresar_nuevamente.place(x=10, y=100)
    ventana_gracias.mainloop()

def ventana_principal():
    ventana = tk.Tk()
    ventana.title("Formulario")
    ventana.geometry("500x350")
    fondo = tk.PhotoImage(file="y.png")
    label_fondo = tk.Label(ventana, image=fondo)
    label_fondo.image = fondo
    label_fondo.place(x=0, y=0, relwidth=1, relheight=1)
    label_nombre = tk.Label(ventana, text="Nombre:")
    label_nombre.place(x=10, y=10)
    entry_nombre = tk.Entry(ventana)
    entry_nombre.place(x=120, y=10, width=360)
    label_edad = tk.Label(ventana, text="Edad:")
    label_edad.place(x=10, y=50)
    entry_edad = tk.Entry(ventana)
    entry_edad.place(x=120, y=50, width=360)
    label_comuna = tk.Label(ventana, text="Comuna:")
    label_comuna.place(x=10, y=90)
    entry_comuna = tk.Entry(ventana)
    entry_comuna.place(x=120, y=90, width=360)
    label_texto = tk.Label(ventana, text="Texto:")
    label_texto.place(x=10, y=130)
    texto_box = tk.Text(ventana)
    texto_box.place(x=120, y=130, width=360, height=100)
    label_opcion = tk.Label(ventana, text="Opción:")
    label_opcion.place(x=10, y=240)
    combobox = ttk.Combobox(ventana)
    combobox['values'] = ('aaa', 'bbb', 'ccc')
    combobox.current(0)
    combobox.place(x=120, y=240, width=360)
    boton_enviar = tk.Button(ventana, text="Enviar", command=lambda: mostrar_datos(entry_nombre, entry_edad, entry_comuna, ventana, texto_box, combobox))
    boton_enviar.place(x=120, y=280, width=360)
    ventana.mainloop()

ventana_principal()